### ISSUE TITLE
NotImplementedException in _model

### ISSUE THREAD

**Issue by AdamBorowiecki** [mpostol/OPC-UA-OOI#231]
During debugging mehod Setup() in file ConsumerDataManagementSetup.cs objet_model have an exception in UAEncoder.

**Comment by mpostol** [comment]
I need more information to reproduce this exception.

**Comment by mpostol** [comment]
This class doesn't have UAEncoder nor objet_model words used.

**Comment by mpostol** [comment]
Because not all types has been implemented by UAEncoder it could happen if the configuration is wrong and not implemented type is expected. Additional diagnostic will help to investigate it in more details. I consider it done for now.
