### ISSUE TITLE
System.Reflection.ReflectionTypeLoadException during loading transport layer(UDP, MQTT or AMQP)

### ISSUE THREAD

**Issue by AdamBorowiecki** [mpostol/OPC-UA-OOI#236]
Sometimes during loading DLL with transport layer(UDP, MQTT or AMQP) System.Reflection.ReflectionTypeLoadException was thrown. This is happens, besause the versions od DLL was incompatible, but the try-catch statement with information  e.g. about LoaderException will be useful.

**Comment by mpostol** [comment]
I have added dedicated exception handling procedure to log the whole exception chain to file, UT has been also added to test this functionality. Hope it solves the problem .
