### ISSUE TITLE
Closing of ReferenceApplication does not cause kill of process is system(sometimes)

### ISSUE THREAD

**Issue by AdamBorowiecki** [mpostol/OPC-UA-OOI#237]
Sometimes closing of ReferenceApplication does not cause kill of process is system and it cause problem with rebuildt Solution. However, a reproduction of this fault is hard.

**Comment by mpostol** [comment]
It is very old and musty be confirmed - check in log if the dispose chain is executed.

**Comment by mpostol** [comment]
Investigate the problem using improved tracing mechanism for bootstrapper and the dispose process.
