### ISSUE TITLE
Port the library UAOOI.Networking.SemanticData to .NET STandard

### ISSUE THREAD

**Issue by mpostol** [mpostol/OPC-UA-OOI#245]
# Description

## Scope

- use [.NET Portability Analyzer](https://marketplace.visualstudio.com/items?itemName=ConnieYau.NETPortabilityAnalyzer) to check the library against portability
- modify the code
- improve testing

Look at this:

[How to port from .net framework to .net standard](https://codehollow.com/2017/05/port-net-framework-net-standard/)

## Related work

- planned Xamarin HMI implementation

**Comment by mpostol** [comment]
To properly manage NuGet packages and avoid UT errors related to the wrong version new solutions must be defined.  It must be converged with this work.

**Comment by mpostol** [comment]
The first priority is to port the projects:
- `Networking.SemanticData`
- `Configuration.Networking`
- `Common.Infrastructure`

Question for users - what requirements must be met to port these libraries? 
E.g.  Does .NET Standard 2.0  meet all requirements to create Xamarin HMI mobile implementation?

**Comment by Drutol** [comment]
Hello, I've successfully built several Xamarin apps using .NET Standard libraries targeting profile:
```xml
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
```
Porting to .Net Standard is the most prospective course of action right now, it'll be possible to run the library within .Net Core 2.0 apps, Xamarin apps etc.

**Comment by mpostol** [comment]
Move it to separate project as it is not related to WPF.
