### ISSUE TITLE
Create and Register the EventSource

### ISSUE THREAD

**Issue by mpostol** [mpostol/OPC-UA-OOI#455]
- [x] [How to: Register the EventSource](https://commsvr.gitbook.io/ooi/reactive-communication/readmegettingstartedtutorial#how-to-register-the-eventsource)
- [x] review the documentation if needed
- [x] review #433 and apply all findings

**Comment by Drutol** [comment]
Added note to commit: https://github.com/mpostol/OPC-UA-OOI/commit/7c18116d227ecee250d7ef5d59737b479697d08c#r42251983

**Comment by mpostol** [comment]
Not all anchors have been resolved.
