### ISSUE TITLE
Implement communication to Azure

### ISSUE THREAD

**Issue by mpostol** [mpostol/OPC-UA-OOI#467]
## Scope

- [x] AzureCommunicationContext
- [x] AzureCommunicationStateBase
- [x] AzureCommunicationRegitering
- [x] AzureCommunicationCommunication
- [x] AzureCommunicationDisconnected

>Note: Out-of-band communication must be implemented using Data Transfer Object concept

**Comment by mpostol** [comment]
Coniseder note [IAsyncDisposable](https://github.com/mpostol/OPC-UA-OOI/commit/34123d82ed0535b072347d5803c942531abc40f3#r41917701)

**Comment by Drutol** [comment]
One thing to note about `IAsyncDisposable` is that it's netstandard2.**1** feature. So it is advised to implement both patterns.
Not sure about blocking the thread in synchronous variant though.

**Comment by mpostol** [comment]
> One thing to note about `IAsyncDisposable` is that it's netstandard2.**1** feature. So it is advised to implement both patterns.
> Not sure about blocking the thread in synchronous variant though (may be worth closing the connection is separate method altogether for sync variant).

IDisposable is not needed anymore.  The state machine is responsible to dispose of all resources.
